# The default difficulty setting
default: normal

# The amount of time, in minutes, that must pass until one's difficulty can be changed
# Setting this value to -1 will make it so that difficulty may only be selected once
time-delay: 120

# Toggles various attributes of the plugin
toggle:
  # If "true" difficulties will affect whether players drop items on death
  keep-inventory: true
  # If "true" difficulties will affect whether players drop experience on death
  keep-xp: true
  # If "true" difficulties will affect how much experience mobs drop
  mob-xp-multiplier: true
  # If "true" difficulties will affect how much experience ores drop
  ore-xp-multiplier: true
  # If "true" difficulties will affect how much damage is done by mobs
  damage-multiplier: true
  # If "true" difficulties will have a chance to double item drops from mobs
  mob-doubled-loot-chance: true
  # If "true" difficulties will have a chance to double item drops from ores
  ore-doubled-loot-chance: true
  # If "true" difficulties will affect the venom of cave spiders and bees
  venom-time: true
  # If "true" difficulties will affect the health at which a player will stop taking damage from starvation
  min-health-starvation: true
  # If "true" the player will drop an amount of money on death specified by their difficulty
  # Requires Vault and an economy plugin to have any effect
  money-lost-on-death: false

# A list of difficulties and their properties.
# You may add or remove difficulties as long as you include values for all difficulty properties (keep-inventory, keep-xp, etc.)
difficulties:

  easy:
    # Sets whether a player keeps their inventory after death
    keep-inventory: true
    # Sets whether a player keeps their experience points after death
    keep-xp: true
    # Sets the multiplier of experience gained from killing mobs
    mob-xp-multiplier: 0.75
    # Sets the multiplier of experience gained from mining blocks and using furnaces
    ore-xp-multiplier: 0.8
    # Sets the multiplier of damage caused by non-player entities
    damage-multiplier: 0.75
    # Sets the chance (where 0.0 is 0% and 1.0 is 100%) that mobs killed by a player will drop double items
    mob-doubled-loot-chance: 0.0
    # Sets the chance that ores broken by a player will drop double items
    ore-doubled-loot-chance: 0.0
    # Sets the time, in seconds, that a cave spider's venom will affect the player
    # Venom from bees will last 3 seconds longer than the time stated below
    # Set to 0 for no poison effect
    venom-time: 0
    # Sets the health at which starvation stops dealing damage to the player where 20 is 10 hearts and 0 is 0 hearts
    min-health-starvation: 10
    # Sets the amount of money lost when a player dies
    # Requires Vault and an economy plugin to have any effect
    money-lost-on-death: 0.0
    # Sets whether this difficulty requires players that use it to have the "idifficulty.diff.[difficulty_name]" permission
    # For example, if set to true for this difficulty, players would need the permission node "idifficulty.diff.easy" to use it
    requires-permission: false

  normal:
    keep-inventory: true
    keep-xp: false
    mob-xp-multiplier: 1.0
    ore-xp-multiplier: 1.0
    damage-multiplier: 1.0
    mob-doubled-loot-chance: 0.1
    ore-doubled-loot-chance: 0.05
    venom-time: 7
    min-health-starvation: 1
    money-lost-on-death: 20.0
    requires-permission: false

  hard:
    keep-inventory: false
    keep-xp: false
    mob-xp-multiplier: 1.5
    ore-xp-multiplier: 1.2
    damage-multiplier: 1.5
    mob-doubled-loot-chance: 0.3
    ore-doubled-loot-chance: 0.1
    venom-time: 15
    min-health-starvation: 0
    money-lost-on-death: 100.0
    requires-permission: false

# DO NOT CHANGE UNDER ANY CIRCUMSTANCES
config-version: 1